### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by boynextdoorqwq** [BananaPuncher714/PublicCrafters#1]
https://i.loli.net/2018/02/02/5a73d255cd4a4.png
Is it BUG?
Can you fix it？:)

**Comment by BananaPuncher714** [comment]
It is a bug inside the ItemDisplay class. Instead of storing the ArmorStand, it needs to use the uuid when removing it. I will push out a new commit when I have time.

**Comment by boynextdoorqwq** [comment]
THANKS!
