### ISSUE TITLE
Supports for 1.20.5+/1.21

### ISSUE THREAD

**Issue by INSide-734** [BananaPuncher714/PublicCrafters#17]

**Comment by Mitality** [comment]
Any predictions on how long it might take you to do?

**Comment by INSide-734** [comment]
> Any predictions on how long it might take you to do?

A week or even months. I don't know.🤷🏻‍♂️

**Comment by Mitality** [comment]
It's been two months since the release of 1.20.5, which indroduced the new component system and it's a paid plugin...

**Comment by Mitality** [comment]
As of now, 1.20.5, 1.20.6 and 1.21 break the plugin, sadly, rendering it completely unusable...

**Comment by INSide-734** [comment]
As far as I know, the author is still trying to adapt the new version.Many people are also asking the author when to update.I also look forward to the author's update.

**Comment by BananaPuncher714** [comment]
I am currently updating NBTEditor, which is a dependency for this plugin. Once I get that done then I can start updating this one.

**Comment by INSide-734** [comment]
> I am currently updating NBTEditor, which is a dependency for this plugin. Once I get that done then I can start updating this one.

That's great. I've been looking forward to this plugin update.

**Comment by INSide-734** [comment]
@BananaPuncher714  When will it be updated？😫😫😫

**Comment by BananaPuncher714** [comment]
This weekend. It took me all of last weekend to update NBTEditor, sorry.
