### ISSUE TITLE
Piston support problem

### ISSUE THREAD

**Issue by rmalca** [BananaPuncher714/PublicCrafters#19]
Hi, I'm trying piston support on my server with Plazma (Paper based) and it doesn't seem to work. I don't know what could be wrong.

First act:
![image](https://github.com/user-attachments/assets/afe98c58-2064-4647-953d-c2148633e365)

Second act:
![image](https://github.com/user-attachments/assets/333075df-dcd4-4bf3-8c3f-e1a6195b7070)

Third act:
![image](https://github.com/user-attachments/assets/bf4bafae-9ae7-4604-acba-f694c896779b)

I also tried changing "update-delay" to 2 (and server full restart) but I don't see any change.

I would try it on paper but I have mobile internet, due to a problem with my Internet provider, and my access is limited.

Thanks in advance.

**Comment by BananaPuncher714** [comment]
Hi, can you try increasing the update-delay to something higher like 20, and slowly decrease it until it stops working? You can reload the config with `/publicrafters reload`. The delay is how soon to teleport the items, but it may not always show up properly client side due to some latency issues.

**Comment by rmalca** [comment]
> Hi, can you try increasing the update-delay to something higher like 20, and slowly decrease it until it stops working? You can reload the config with `/publicrafters reload`. The delay is how soon to teleport the items, but it may not always show up properly client side due to some latency issues.

I changed update-delay to 20 with a vanilla client (no mods) and a Paper 1.20.6 server but unfortunately the problem continues.

**Comment by BananaPuncher714** [comment]
Ok thanks, I will take a look at this and get back to you.
