### ISSUE TITLE
why again？

### ISSUE THREAD

**Issue by boynextdoorqwq** [BananaPuncher714/PublicCrafters#2]
https://i.loli.net/2018/02/23/5a8f70260e377.png

**Comment by BananaPuncher714** [comment]
Do you have an armorstand editing plugin? Also, are you using the latest version? Can you tell me what server version you have?

**Comment by BananaPuncher714** [comment]
This should be fixed by now. The virtual armorstands option will prevent any duplication as well. Reopen this issue or start a new one if you still have this problem.
