### ISSUE TITLE
warn on server start

### ISSUE THREAD

**Issue by homerek111** [BananaPuncher714/PublicCrafters#20]
hello im getting this warn on server start:
https://pastebin.com/AFSaCS2v

**Comment by BananaPuncher714** [comment]
Thanks, what paper version are you using?

**Comment by homerek111** [comment]
> Thanks, what paper version are you using?

This server is running Paper version 1.21.1-83-master@2aaf436 (2024-09-17T15:10:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
