### ISSUE TITLE
Question: Purchasing vs Building from Source

### ISSUE THREAD

**Issue by A248** [BananaPuncher714/PublicCrafters#3]
Hello,

I understand PublicCrafters is a premium plugin. However, it is also here, open-source. Though I have not attempted, it is possible to build from source, no? That, then, would allow one to use the plugin free of charge.

In no way would I ever violate your rights as a developer; I fully respect your right to charge for PublicCrafters. I am just wondering if it is acceptable to use PublicCrafters without paying via SpigotMC.

Thanks for your understanding,

A248

**Comment by BananaPuncher714** [comment]
Hello, sorry for the late reply. Yes you can use PublicCrafters for free if you build from source. I don't mind if you want to do so, but I only offer support for those who purchase it on SpigotMC.

**Comment by A248** [comment]
Thank you for the clarification! I'm very glad to be able to use it without purchasing.
